Lkolluru/encryptpergcspath
byronwhitlock-google/go-gcsproxy pull request #15
Opened 2024-12-11 14:56 UTC by lkolluru05

2024-12-11 16:06 UTC, byronwhitlock-google requested changes

2024-12-11 16:06 UTC, byronwhitlock-google commented on gcs-proxy.go
Please rename this function 
getBucketNameSimpleDownload => getBucketNameFromRequestUri

2024-12-11 16:06 UTC, byronwhitlock-google commented on handle-multipart-upload.go
Please rename getBucketNameMultipartUpload => getBucketNameFromGcsMetadata

2024-12-11 16:06 UTC, byronwhitlock-google commented on main.go
Do not override these defaults. You should set environment variables for testing.

2024-12-11 16:06 UTC, byronwhitlock-google commented on main.go
Also set default for KmsBucketKeyMapping  to empty.

2024-12-11 16:06 UTC, byronwhitlock-google commented on main.go
There is no validation for KmsBucketKeyMapping. Each key needs to be validated to make sure we have acceess to the key. see CheckKms() function.

2024-12-11 16:06 UTC, byronwhitlock-google commented on main.go
KmsBucketKeyMapping is NOT exposed through an environment variable. this needs to be exposed. Make sure to update the usage() function to reflect the name change.

2024-12-11 16:13 UTC, byronwhitlock-google commented on gcs-proxy.go
Make sure to check EVERY function to check to passthru or not.  Every method mutliPartupload, singleUpload, singleDownload etc enumeration should have a check.  **very important*** This will cause major bugs if not implemented.

2024-12-11 16:26 UTC, byronwhitlock-google requested changes
Please test this in all combinations.

Case1:
KMS_RESOURCE_NAME is set
KMS_RESOURCE_KEY_MAP is unset
Desired result: use KMS_RESOURCE_NAME unconditionally

Case2:
KMS_RESOURCE_NAME is unset
KMS_RESOURCE_KEY_MAP set
Result: Use KMS_RESOURCE_KEY_MAP

Case3:
KMS_RESOURCE_NAME is set
KMS_RESOURCE_KEY_MAP set
Result: ERROR "Cannot set both"

Case4:
KMS_RESROUCE_KEY_MAP set =  bucket1:key1
Request to bucket2 happens
Expected Result: bucket2 is passthru

Case5
KMS_RESROUCE_KEY_MAP set = bucket1:key1,bucket2:key2
Request to bucket2 happens
Expected Result: bucket2 is encrypted/decrypted by key2

Case6
KMS_RESROUCE_KEY_MAP set = bucket1:key1,bucket2:key2
Request to bucket1 happens
Expected Result: bucket1 is encrypted/decrypted by key1
etc, etc.

2024-12-12 08:21 UTC, lkolluru05 commented on main.go
code updated, need an other eye

2024-12-12 08:42 UTC, lkolluru05 commented
> Please test this in all combinations.
> 
> Case1: KMS_RESOURCE_KEY_MAP is unset Desired result: Error
> 
> Case4: KMS_RESROUCE_KEY_MAP set = bucket1:key1 Request to bucket2 happens Expected Result: bucket2 is passthru
> 
> Case5 KMS_RESROUCE_KEY_MAP set = bucket1:key1,bucket2:key2 Request to bucket2 happens Expected Result: bucket2 is encrypted/decrypted by key2
> 
> Case6 KMS_RESROUCE_KEY_MAP set = bucket1:key1,bucket2:key2 Request to bucket1 happens Expected Result: bucket1 is encrypted/decrypted by key1 etc, etc.

2024-12-12 18:15 UTC, byronwhitlock-google commented
Please make the change so depending on the configuration setting, either the KMS_RESOURCE_NAME  or KMS_RESOURCE_KEY_MAP is used NEVER BOTH. right now the simpleDownload uses KMS_RESOURCE_KEY_NAME while the upload uses KMS_RESOURCE_KEY_MAP. 

Please check these additional test cases

Case1:
KMS_RESOURCE_NAME is set
KMS_RESOURCE_KEY_MAP is unset
Desired result: use KMS_RESOURCE_NAME unconditionally

Case2:
KMS_RESOURCE_NAME is unset
KMS_RESOURCE_KEY_MAP set
Result: Use KMS_RESOURCE_KEY_MAP

Case3:
KMS_RESOURCE_NAME is set
KMS_RESOURCE_KEY_MAP set
Result: ERROR "Cannot set both" proxy fails to start.

2025-01-06 18:26 UTC, byronwhitlock-google approved these changes

2025-01-06 18:26 UTC, merged